version: '3.8'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - neria-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=neria-gateway"
      - "traefik.http.routers.sportstay.rule=Host(`sportstay.neriaintelligence.com.br`)"
      - "traefik.http.routers.sportstay.entrypoints=websecure"
      - "traefik.http.routers.sportstay.tls.certresolver=myresolver"
      - "traefik.http.services.sportstay.loadbalancer.server.port=80"

networks:
  neria-gateway:
    external: true
